package com.astaroth.listacompra.dep.storage.db;

interface DBConstants {

	String DATABASE_NAME = "ListaCompra";
	int DATABASE_VERSION = 1;

	String TABLE_COLLECTIONS = "collections";
	String COLUMN_COLLECTION_ID = "_id";
	String COLUMN_COLLECTION_DESCRIPCION = "description";
	String COLUMN_COLLECTION_TYPE = "type";
	String[] CAMPOS_COLLECTIONS = new String[] { COLUMN_COLLECTION_ID, COLUMN_COLLECTION_DESCRIPCION, COLUMN_COLLECTION_TYPE };
	int COLUMN_COL_ID_POSITION = 0;
	int COLUMN_COL_DESCRIPTION_POSITION = 1;
	int COLUMN_COL_TYPE_POSITION = 2;

	int COL_TYPE_BOOK = 0;
	int COL_TYPE_FILM = 1;
	int COL_TYPE_TRAVEL = 2;
	int COL_TYPE_TROLLEY = 3;
	int COL_TYPE_MUSIC = 4;
	int COL_TYPE_PRESENT = 5;
	int COL_TYPE_FOOD = 6;
	int COL_TYPE_INDEFINIED = 7;

	String TABLE_DETAILS = "details";
	String COLUMN_DETAILS_ID = "_id";
	String COLUMN_DETAILS_DESCRIPCION = "description";
	String COLUMN_DETAILS_NAME = "name";
	String COLUMN_DETAILS_IDCOLLECTION = "idCollection";
	String COLUMN_DETAILS_CANTIDAD = "quantity";
	String COLUMN_DETAILS_IMPORTE = "amount";
	String COLUMN_DETAILS_MARCADO = "mark";
	String[] CAMPOS_DETAILS = new String[] { COLUMN_DETAILS_ID, COLUMN_DETAILS_DESCRIPCION, COLUMN_DETAILS_NAME, COLUMN_DETAILS_CANTIDAD, COLUMN_DETAILS_IDCOLLECTION, COLUMN_DETAILS_IMPORTE, COLUMN_DETAILS_MARCADO };
	int COLUMN_DET_ID_POSITION = 0;
	int COLUMN_DET_DESCRIPTION_POSITION = 1;
	int COLUMN_DET_NAME_POSITION = 2;
	int COLUMN_DET_CANTIDAD_POSITION = 3;
	int COLUMN_DET_COLLECTION_POSITION = 4;
	int COLUMN_DET_IMPORTE_POSITION = 5;
	int COLUMN_DET_MARCADO_POSITION = 6;

}
